name: E2E Cypress Testing
on:
  pull_request:
    branches:
      - main
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          config: pageLoadTimeout=100000,baseUrl=https://filmq-git-dev-sambrock.vercel.app/
        env:
          # pass GitHub token to detect new build vs re-run build
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          DATABASE_URL: ${{secrets.DATABASE_URL}}
          SHADOW_DATABASE_URL: ${{secrets.SHADOW_DATABASE_URL}}
