name: E2E Cypress Testing
on:
  pull_request:
    branches:
      - main
jobs:
  e2e-cypress:
    runs-on: ubuntu-latest
    container: cypress/included:8.3.1
    steps:
      - name: Run Cypress Tests
        run: cypress run --headless --browser chrome --config baseUrl=https://filmq-git-dev-sambrock.vercel.app/
